### ISSUE TITLE
Request: Epilepsy-friendly "dirty cheater" config

### ISSUE THREAD

**Issue by lxkm** [SlimeKnights/IguanaTweaksTConstruct#145]
So I just got hit earlier by the "dirty cheater" effect for the first time. As a photosensitive epileptic I already have to watch out somewhat in games, but Minecraft isn't normally an issue. The *massive* cloud of fake xp orbs that the dirty cheater event causes *is* an issue though. The screen effect caused one of the worst seizures I've had in years. Consequently I am more than a little peeved.

I had a look for an option to disable any part or all of the feature, but couldn't find anything. Therefore, I would like to request two things (the first as a definite, the second I'm not so bothered about):

1. An option to disable the fake xp orb spam.
2. The option to completely disable the dirty cheater effect. Yes it breaks balance when the Mmms dummy is in game, but some people don't care. Personally I'd be happy with it being an opt-out option (so normally on), just as long as the visual effect can be cancelled.

Thank you.

**Comment by bonii-xx** [comment]
I'm sorry to hear that, and hope you are well.
However the effect is not worse than a vanilla XP farm or openblocks XP shower. The problem here seems not to be the feature, but the rather bright and hectic blinking of the XP orbs. I suggest you look into a resource pack that reduces or removes the effect from the XP orb graphics, or you're always at risk of running into similar situations, since modded minecraft relies on 3rd party content.
As for the context of ITT the problem is easily solved: Don't hit dead entities.
