### ISSUE TITLE
Part replacement with stone parts not working

### ISSUE THREAD

**Issue by BuzzWilson** [SlimeKnights/IguanaTweaksTConstruct#156]
The part replacement does not allow the me to change any part if there is a part made of stone.

Forge Version: 10.13.4.1448
TC Version: 1.8.5
ITT Version: 2.1.5

**Comment by bonii-xx** [comment]
Can't replace parts on tools that couldn't have been built in the first place.

**Comment by BuzzWilson** [comment]
You can if you have the config was set to allow you

**Comment by bonii-xx** [comment]
Then some of the other restrictions apply or your configs are messed up.

**Comment by Gunner76th** [comment]
@BuzzWilson I suggest posting all of your configs related to ITT and Tcon (via pastebin links) to here so that the mod authors can look at them and perhaps find the issue that is eluding you. I had an issue with my configs being reset, and through their help was able to identify the cause of the issue. 

Just like with crashes, providing as much information as possible helps everyone involved, otherwise they are only able to take guesses at the situation based on the limited or lack of information presented.
