### ISSUE TITLE
Non-TConstruct Mining level tweak

### ISSUE THREAD

**Issue by DarklingGX** [SlimeKnights/IguanaTweaksTConstruct#71]
So IguanaTweaks changes mining levels n such, which is cool and all, but I have one problem. The option to deduct a mining level applies to non-TConstruct tools. Is there any way that there could be a config option to exclude these from the nerf? It bugs me that an Awakened Ichorium Pickaxe can't mine cobalt, general stuff like that

**Comment by UndeadZeratul** [comment]
You can always change the Ichorium Pickaxe yourself in the toolOverrides.cfg file, as we've done [here](https://github.com/Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen/blob/master/config/IguanaTinkerTweaks/ToolOverride.cfg#L1225-L1251).  Just set it to whatever harvest level is highest, or even just something crazy high like 50 so that it mines everything.

**Comment by DarklingGX** [comment]
Where is this file located? I can't find it in the config folder.

**Comment by bonii-xx** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2176855-iguanas-tinker-tweaks
